spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: root
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    rest:
      base-path: api
  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB
server:
  error:
    include-message: always
