spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lesson2
    username: postgres
    password: root
#    for @Lob attachment
    hikari:
      auto-commit: false

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#    for data-rest
  data:
    rest:
      base-path: api
#      for attachment
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
server:
  error:
    include-message: always
