###
GET http://localhost:8080/api/category

###
GET http://localhost:8080/api/category/1

###
POST http://localhost:8080/api/category
Content-Type: application/json

{
  "name": "Electronic",
  "active": true
}
