###
GET http://localhost:8080/api/input

###
GET http://localhost:8080/api/input/2

###
POST http://localhost:8080/api/input
Content-Type: application/json

{
  "date": "2022-03-12",
  "warehouseId": 4,
  "supplierId": 1,
  "currencyId": 2,
  "factureNumber": "INV-12345"
}
