###
POST http://localhost:8080/api/user
Content-Type: application/json

{
  "firstname": "Maria",
  "lastname": "Jones",
  "phoneNumber": "123324237411",
  "password": "PassWorD@123",
  "warehouseId": [
    1,
    4,
    1,
    1
  ]
}

###
PUT http://localhost:8080/api/user/2
Content-Type: application/json

{
  "firstname": "Miss Maria",
  "lastname": "Jones",
  "phoneNumber": "123324237411",
  "password": "PassWorD@123",
  "warehouseId": [
    1,
    2,
    4,
    1,
    1
  ]
}

###
GET http://localhost:8080/api/user

###
GET http://localhost:8080/api/user/1

###
DELETE http://localhost:8080/api/user/1
